### ISSUE TITLE
MKII Rev C Prototype Testing Issues and Observations

### ISSUE THREAD

**Issue by petermccloud** [mccloudaero/evpr#58]
Issues found during testing
1. **Power Management Status** - USING_BAT and USING_ENG appear to be switched? Verified that the correct pins are being used from the schematic.
- **No Power** - USING_BAT=0, USING_ENG=0
- **Batteries Connected** - USING_BAT=0, USING_ENG=1
- **Vraw Only Connected** - USING_BAT=1, USING_ENG=0

2. **Battery 2 Voltage** - When both batteries are disconnected, but power is applied to VRAW, battery 2 voltage appears to have a battery?

- BAT_EN=1 and ENG_EN=1
  - **Bat 2 only** - Vraw: 430mV Bat 1: 245mV Bat 2: 1363mV
  - **Bat 1 & 2** Vraw: 430mV Bat 1: 3737mV Bat 2: 4377mV
  - **Vraw only**  Vraw: 7514mV Bat 1: 245mV Bat 2: 4377mV

- BAT_EN=1 and ENG_EN=0
  - **Bat 2 only** Same
  - **Bat 1 only** Same
  - **Vraw only** 7536mV Bat 1: 245mV Bat 2: 2122mV

Other Observations
- Vraw voltage decays slowly after disconnect - Just something to be aware of for health checking

**Comment by GeorgesOatesLarsen** [comment]
Closed -- all observed issues have been confirmed to be caused by fabrication issues -- Revision D has updated to accommodate this
